version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.init
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: lifecycle
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifecycle -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DATABASE_URL: db
      DATABASE_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy 